# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-15 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt_type',
            field=models.IntegerField(choices=[('Practice', '0'), ('Quiz', '0')]),
        ),
    ]
