# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180415_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt_type',
            field=models.IntegerField(choices=[(1, 'Practice'), (2, 'Quiz')]),
        ),
    ]
