# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 01:11
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
